// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package machine

import (
	"CrabGo/api/machine"
)

type ControllerV1 struct{}

func NewV1() machine.IMachineV1 {
	return &ControllerV1{}
}
