// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"CrabGo/internal/dao/internal"
)

// sysUserTokenDao is the data access object for the table SysUserToken.
// You can define custom methods on it to extend its functionality as needed.
type sysUserTokenDao struct {
	*internal.SysUserTokenDao
}

var (
	// SysUserToken is a globally accessible object for table SysUserToken operations.
	SysUserToken = sysUserTokenDao{internal.NewSysUserTokenDao()}
)

// Add your custom methods and functionality below.
