// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"CrabGo/internal/dao/internal"
)

// sysOnlineUserDao is the data access object for the table SysOnlineUser.
// You can define custom methods on it to extend its functionality as needed.
type sysOnlineUserDao struct {
	*internal.SysOnlineUserDao
}

var (
	// SysOnlineUser is a globally accessible object for table SysOnlineUser operations.
	SysOnlineUser = sysOnlineUserDao{internal.NewSysOnlineUserDao()}
)

// Add your custom methods and functionality below.
