// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"CrabGo/internal/dao/internal"
)

// sysUserRoleDao is the data access object for the table SysUserRole.
// You can define custom methods on it to extend its functionality as needed.
type sysUserRoleDao struct {
	*internal.SysUserRoleDao
}

var (
	// SysUserRole is a globally accessible object for table SysUserRole operations.
	SysUserRole = sysUserRoleDao{internal.NewSysUserRoleDao()}
)

// Add your custom methods and functionality below.
