// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"CrabGo/internal/dao/internal"
)

// sysOrgDeptDao is the data access object for the table SysOrgDept.
// You can define custom methods on it to extend its functionality as needed.
type sysOrgDeptDao struct {
	*internal.SysOrgDeptDao
}

var (
	// SysOrgDept is a globally accessible object for table SysOrgDept operations.
	SysOrgDept = sysOrgDeptDao{internal.NewSysOrgDeptDao()}
)

// Add your custom methods and functionality below.
