// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"CrabGo/internal/dao/internal"
)

// sysLocalizerDao is the data access object for the table SysLocalizer.
// You can define custom methods on it to extend its functionality as needed.
type sysLocalizerDao struct {
	*internal.SysLocalizerDao
}

var (
	// SysLocalizer is a globally accessible object for table SysLocalizer operations.
	SysLocalizer = sysLocalizerDao{internal.NewSysLocalizerDao()}
)

// Add your custom methods and functionality below.
