// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package code

import (
	"CrabGo/api/code"
)

type ControllerV1 struct{}

func NewV1() code.ICodeV1 {
	return &ControllerV1{}
}
